name: Validate
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Checks
        run: pnpm check

      - name: Build
        run: pnpm build

      - name: Tests
        run: pnpm test:coverage
